version: '3.4'

services:
  sqldata:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5433:1433"
  alzaproductapi:
    image: ${DOCKER_REGISTRY-}alzaproductapi
    build:
      context: .
      dockerfile: AlzaProductApi/Dockerfile
    ports:
      - "35555:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      #- ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_URLS=http://+:80
      - ConnectionString=Server=sqldata;Database=AlzaProduct;User Id=sa;Password=Pass@word
    depends_on:
      - sqldata